// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbaqpokreipighxandup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiYXFwb2tyZWlwaWdoeGFuZHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4NTYzNzgsImV4cCI6MjA3NjQzMjM3OH0.w8owYEoIwwwNkvGtSuHj-IxdvHiUHvv1i_Mey4Yqmz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});